version: 1.0.{build}
max_jobs: 8
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
environment:
  appveyor_configuration: Debug
build_script:
- cmd: >-
    @echo off

    dotnet clean

    dotnet restore

    dotnet build
artifacts:
- path: '*.nupkg'
  name: NuGet Package
artifacts:
- path: artifacts\*.nupkg
  name: NuGet Package
deploy:
- provider: NuGet
  server: https://www.myget.org/F/ollon-buildtools/api/v2/package
  api_key:
    secure: V2NEKChHJzhrkA/4KGHfAmkf+BijIbODnmzNgHMem3VTglZzCzb4slOpNnMBtrmu
  skip_symbols: true
  artifact: NuGet Package